name: Generate Cloud Incidents JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  fetch-incidents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install script dependencies
        run: |
          npm init -y
          npm install xml2js

      - name: Run script
        run: node scripts/fetch-cloud-incidents.js

      - name: Commit incidents file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add cloud-incidents.json
          git commit -m "Update incidents data" || echo "No changes"
          git push
